version: "2.3"
services:
  keycloak-container:
    image: jboss/keycloak:16.1.1
    command: 
      # -Djboss.socket.binding.port-offset=200
    restart: always
    environment:
      KEYCLOAK_USER: turreta
      KEYCLOAK_PASSWORD: 4909cbfa-2aba-4a30-836d-12b6d468a311
    ports:
      - 8080:8080
      # - 8280:8280
    networks:
      - turreta_network    
networks:
  turreta_network:
    driver: bridge
